### ISSUE TITLE
[PHB] Typos and Fixes

### ISSUE THREAD

**Issue by NickVendel** [AuroraLegacy/elements#69]
- [ ] - Arcane Recovery's sheet description doesn't mention that regained slots cannot be of level 6 or higher.
- [ ] - Simulacrum's material component has copy-paste issues, and is written incorrectly in general.

**Comment by kgirtxd** [comment]
Can we add the table to the wild shape description and add info to the sheet explaining what your limits are for the creatures you can become?
![image](https://user-images.githubusercontent.com/15676362/115643626-b650f680-a2e2-11eb-93b1-c049cd3f94d7.png)

**Comment by kgirtxd** [comment]
Bigby's hand description formatting.  Currently just a wall of text.

**Comment by kgirtxd** [comment]
Eyebite, Asleep. The target GALLS unconscious

**Comment by Tel0k** [comment]
Criminal background, Bond selection typo in item 6: "Someone I loved died because of I mistake I made. That will never happen again." Should be "of a mistake"

**Comment by Akhistotle** [comment]
Paladin Divine Smite is incorrectly listed as having a maximum of 6d8 radiant damage, despite the maximum being 5d8 when not used against fiends or undead.
![image](https://user-images.githubusercontent.com/96489625/146963813-a1b134ba-cdf1-45e9-b8c6-fa6050b6e7e5.png)

**Comment by kgirtxd** [comment]
> Paladin Divine Smite is incorrectly listed as having a maximum of 6d8 radiant damage, despite the maximum being 5d8 when not used against fiends or undead. ![image](https://user-images.githubusercontent.com/96489625/146963813-a1b134ba-cdf1-45e9-b8c6-fa6050b6e7e5.png)

This was fixed in #5 so your core files may still be set to the original archive.  The current paladin file is version 0.3.2

**Comment by Akhistotle** [comment]
> > Paladin Divine Smite is incorrectly listed as having a maximum of 6d8 radiant damage, despite the maximum being 5d8 when not used against fiends or undead. ![image](https://user-images.githubusercontent.com/96489625/146963813-a1b134ba-cdf1-45e9-b8c6-fa6050b6e7e5.png)
> 
> This was fixed in #5 so your core files may still be set to the original archive. The current paladin file is version 0.3.2

I've wiped and redownloaded the core files and still have the typos, any advice on the fix?

**Comment by NickVendel** [comment]
@CrustytheClown do you have a discord? If so, join our server you can find in README so we can help you with that problem faster
